
<html>
<head>
<link rel="stylesheet" type="text/css"
	href="http://www.quantumstreams.net/css/bootstrap.css">
<title>Quantum Streams</title>
<style>
.page-empty {
	background-attachment: fixed;
	background-image:
		url("http://bnrfilms.in/wp-content/uploads/2014/08/website-background-small3.jpg");
	background-size: 100% 100%;
	margin: 0;
}
</style>
</head>
<body>
	<script src="http://www.quantumstreams.net/css/jquery-2.1.1.js"></script>
<script src="http://www.quantumstreams.net/quantum.js"></script>
	<div style="padding: 0; margin: 0; width: 100%;" class="container">
		<div class="col-xs-12 col-sm-12 col-md-12"
			style="background: none repeat scroll 0px 0px rgba(255, 255, 255, 0.7); border: 1px #999 solid; color: white;">

			<div class="" style="float: left;display:inline-flex">
				<a href="<?php echo $this->getBaseUrl();?>"><img
					src="http://www.quantumstreams.net/logo_q.png"
					style="height: 60px; padding: 10px;" /></a>
				
			</div>

			<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){?>
			<div class="" style="float: right;">

				<a class="linkOnTop"
					href="<?php echo $this->getBaseUrl();?>customer/account/logout">Logout
					|</a>
			</div>
			<div class="" style="float: right;">
				<a onclick="help()" href="#"
					class="linkOnTop">Help |</a>
			</div>
								
			
			<?php }else{?>
<div id="fb-root"></div>
<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()):?>

	<a href="#" onclick="return fblogin();" class="fb_button_ps"><img
				style="margin: 10px; float: right;" height="40px"
				src="http://www.mygrocerybag.in/media/facebook-con.png"
				alt="<?php echo $this->__('Connect with Facebook')?>" /></a>
				
			
<?php endif?>

<?php }?>
		</div>
		<div style="padding: 0" class="col-xs-12 col-sm-12 col-md-12">

			<div
				style="padding: 0;overflow:hidden; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2); opacity: 0; border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe2">
				
				
		<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){?>		
		<?php echo '<h3 style="font-size: 1.1em;margin: 0; font-weight: bold;color: white;padding: 10px;  background: rgba(0,0,0,0.7); padding-left:15px">My Saved Streams:</h3>';?>
<div id="streamList"
					style="margin-bottom: 4px; color: black; max-width: 100%; width: 100%; overflow-x: hidden; overflow-y: scroll; background: rgba(255, 255, 255, 0.6); border: 1px solid white; z-index: 999;">
<?php ?>
				</div>
<?php }else{?>
<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 1 -->
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="5762717689"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<?php }?>
<div class="col-sm-12 col-md-12 col-xs-12" style="height: 60px;" id="inputBox">
<p style="font-weight:bold;color:white;margin: 2px;background: rgba(0,0,0,0.8); padding-left:10px;">Enter stream name:</p>
					<input id="inputName" class="col-md-8 col-xs-8 col-sm-8">
					<button style="background: green;color:white;line-height: 20px" class="col-xs-4 col-md-4 col-sm-4" id="inputOk"
						onclick="restream()">Save</button>
				</div>
			</div>



			<div class="col-xs-8 col-sm-8 col-md-8"
				style="background: none repeat scroll 0px 0px rgba(255, 255, 255, 0.5); color: white; border: 1px #999 solid;">

				<div style="padding: 0;" class="col-xs-12 col-sm-12 col-md-12">
					<object
						style="position: relative; display: none; min-height: 100%; max-width: 100%;"
						id="content-game" data="" height="100%" width="100%">
						<param name="scale" value="exactfit">
					</object>
					<div id="overlayOn"
						style="display: none; width: 100%; min-height: 100%; max-width: 100%; height: 100%; background: url('http://www.quantumstreams.net/atom_animated.gif') no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;"></div>
					<div id="overlayHelp"
						style="display: none; padding: 25px; width: 100%; text-align: center; height: 100%; background: no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;">
						<h2 style="padding: 10px;">Welcome to QuantumStreams.net</h2>
						<h3>where things are never the same twice.</h3>
						<h4>Randomize Your World</h4>
						<p>You will get a random game inside center window of website. To start click "Next random game". If you don't like random game that was given to you, just click "Next random game", QuantumStreams provides 10000+ game links, so there are various kind of games. If you like the random game and you want to play it in the future, to save it click "Save to list" then give name that you will recognize it by afterward inside input box that appears on the bottom of list, then click Save next to it, because it's very small possibility that you will play this game ever again. To be able to save game into list, create an account on QuantumStreams.net by clicking on "Connect with Facebook". As soon as you register you will get list from left side where your saved games are.</br> QuantumStreams.net is not saving any data except your email to our server.</p>
						<h6>Have fun and enjoy new and entertaining stream links.</h6>
						<h7 style="float:right;"> Best regards, QuantumStreams.Net </h7>
					</div>
					<div onclick="first()" id="firstScreen"
						style="display: block; width: 100%; cursor:pointer; min-height: 100%; max-width: 100%; height: 100%; background: url('http://www.quantumstreams.net/games-start.jpg') no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;"></div>
					
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12"
					style="padding: 5px; position: relative; bottom: 0; right: 0;">
					<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){?>
					<div class="col-xs-6 col-sm-6 col-md-6"
						style="height: 100%;">
						<button onclick="restreamStart();"
							style="width: 100%;text-shadow: 0.5px 0.5px #333; height: 100%; background: rgba(0, 170, 255, 0.8); border: 1px #333 solid; color: white; height: 100%; padding-right: 5px; line-height: 25px; font-size: 1.2em; font-weight: bold;">Save
							game to list</button>
					</div>
					<?php }else{?>
					<div class="col-xs-6 col-sm-6 col-md-6"
						style="height: 100%;"><button onclick="restreamAlert();"
							style="width: 100%; text-shadow: 0.5px 0.5px #333;height: 100%; background: rgba(0, 170, 255, 0.8); border: 1px #333 solid; color: white; height: 100%; padding-right: 5px; line-height: 25px; font-size: 1.2em; font-weight: bold;">Save
							game to list</button></div>
					<?php }?>
					<div class="col-xs-6 col-sm-6 col-md-6"
						style="height: 10%; padding: 0;">
						<button onclick="skip();"
							style="width: 100%;text-shadow: 0.5px 0.5px #333; height: 100%; background: rgba(255, 100, 100, 0.8); border: 1px #333 solid; color: white; height: 100%; padding-left: 5px; line-height: 25px; font-size: 1.2em; font-weight: bold;">Next
							random game</button>
					</div>
				</div>
					<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()):?>
				<h4 class="col-xs-12 col-sm-12 col-md-12" style="background-color:rgba(0,50,0,0.6);text-shadow: 0.5px 0.5px #333;line-height:30px;text-align:center;font-weight:bold;color:white; float: left;cursor:pointer;border:2px solid #333;padding:5px;"><a style="color:white;" onclick="help()" href="#">Click here for instructions.</a></h4>
<?php endif?>
			</div>


			<div
				style="overflow: hidden; padding: 0; margin-bottom: 4px; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2); opacity: 0; border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe">

				<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 2 -->
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="7239450882"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
			</div>

		</div>
	</div>

	<script>

function help(){
	$('#content-game').hide();
	$('#overlayOn').hide();
	$('#firstScreen').hide();
	$('#overlayHelp').show();
	
}

function restreamAlert(){
	alert('You must login to be able to use this feature :)');
}
</script>




</body>
</html>
