
<html>
<head>
<link rel="stylesheet" type="text/css"
	href="http://www.quantumstreams.net/css/bootstrap.css">
<title>Quantum Streams</title>
<style>
.wrapper {
	background-image:
		url("http://www.hdwallpapers.in/walls/fantasy_space-wide.jpg");
	background-size: 100% 100%;
	margin: 0;
}
</style>
</head>
<body>
	<script src="http://www.quantumstreams.net/css/jquery-2.1.1.js"></script>

	<div style="padding: 0; margin: 0; width: 100%;" class="container">
		<div class="col-xs-12 col-sm-12 col-md-12"
			style="background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.8); border: 1px #999 solid; color: white;">
<div class="" style="float: left;">
				<a href="<?php echo $this->getBaseUrl();?>"><img
					src="http://www.quantumstreams.net/logo_q.png"
					style="height: 60px; padding: 10px;" /></a>
			</div>
			<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){?>
			<div class="" style="float: right;">
			
				<a class="linkOnTop"
					href="<?php echo $this->getBaseUrl();?>customer/account/logout">Logout
					|</a>
			</div>
			<div class="" style="float: right;">
				<a href="<?php echo $this->getBaseUrl();?>flashgames/myprofile"
					class="linkOnTop">My Profile |</a>
			</div>
			
						<div class="" style="float: right;">
				<a class="linkOnTop"
					href="<?php echo $this->getBaseUrl();?>flashgames/mystreams">My
					Streams |</a>
			</div>
<?php }else{?>
<img style="margin:10px;float:right;" height="40px" src="http://www.mygrocerybag.in/media/facebook-con.png"/>
<?php }?>
		</div>
		<div style="padding: 0" class="col-xs-12 col-sm-12 col-md-12">

			<div
				style="padding: 0; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2);opacity:0; border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe2">
				<!--  script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 1 
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="5762717689"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script -->
			</div>



			<div class="col-xs-8 col-sm-8 col-md-8"
				style="background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.7); color: white; border: 1px #999 solid;">

				<div style="padding: 0;" class="col-xs-12 col-sm-12 col-md-12">
					<object
						style="position: relative;display:none; min-height: 100%; max-width: 100%;"
						id="content-game"
						data=""
						height="100%" width="100%">
						<param name="scale" value="exactfit">
					</object>
					<div id="overlayOn"
						style="display: none; width: 100%;  height: 100%; background: url('http://www.quantumstreams.net/atom_animated.gif') no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;"></div>
					<div id="firstScreen"
						style="display: block;padding: 25px; width: 100%; text-align: center;  height: 100%; background: no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;">
						<h1 style="padding:20px;">Welcome to QuantumStreams.net</h1>
						<h1 style="color:blue;"><a onclick="first();" style="cursor:pointer">Click to play :)</a></h1>
						
						<p style="color:red;">THIS IS BETA VERSION - PROFILES ARE NOT IMPLEMENTED YET (just click and play)</p>
						<h3>You will get random game inside this window.</h3>

<p>If you like a game you can save it into your list, because it's very small possibility you will get the same stream link ever again, until saved.
</p>
<p>
To save it click "Restream" button, this will share this game (stream link) with your friends on Facebook and save it into your "My Streams" tab.
</p>
<p>
Skips are limited to 15, and every connected account have 15 in start, if you want new skip all you need to do is "Restream" and get 15 more skips.
</p>
<h4>
Have fun and enjoy new and entertaining stream links.
</h4>
<h5>
Best regards, QuantumStreams.Net
</h5>
<p style="text-align: center; ">
Click <a onclick="first();" style="cursor:pointer">here</a> to start </p>
</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12" style="padding: 5px;">
					<div class="col-xs-6 col-sm-6 col-md-6"
						style="height: 100%; padding: 0;">
						<button onclick="restream();"
							style="width: 100%; height: 100%; background: rgba(0, 170, 255, 0.6); border: 1px #999 solid; color: white; height: 100%; padding-right: 5px; line-height: 25px; font-size: 1.2em; font-weight: bold;">Restream</button>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6"
						style="height: 10%; padding: 0;">
						<button onclick="skip();"
							style="width: 100%; height: 100%; background: rgba(255, 100, 100, 0.6); border: 1px #999 solid; color: white; height: 100%; padding-left: 5px; line-height: 25px; font-size: 1.2em; font-weight: bold;">Skip</button>
					</div>
				</div>
			</div>


			<div
				style="padding: 0; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2);opacity:0;border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe">

				<!--  script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 2 
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="7239450882"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script -->
			</div>

		</div>
	</div>

	<script>
function restream(){
	window.open("https://www.facebook.com/sharer/sharer.php?u=http://www.quantumstreams.net/index.php/flashgames&t=Join the club and expirience funny and random");
}

function firstC(){
	$('#firstScreen').attr("height",(($(window).height()*0.8)+15)+"px");
	$('#firstScreen').attr("width",(($(window).width()*0.7)-30)+"px");
}

function resize(){
	$('#content-game').attr("height",(($(window).height()*0.8)+15)+"px");
	$('#content-game').attr("width",(($(window).width()*0.7)-30)+"px");
	$('#overlayOn').attr("height",(($(window).height()*0.8)+15)+"px");
	$('#overlayOn').attr("width",(($(window).width()*0.7)-30)+"px");

	
}

function skip(){
	
	$('#content-game').hide();
	$('#firstScreen').hide();
	$('#ovoJe').css("opacity","1");
	$('#ovoJe2').css("opacity","1");
	$('#overlayOn').show();
	$('#overlayOn').css("height",(($(window).height()*0.8)+15)+"px");
	$('#overlayOn').css("width",(($(window).width()*0.7)-30)+"px");
	$('#content-game').attr("data","");
	$.get('<?php echo $this->getBaseUrl();?>/flashgames/random/index', function (data, status) {
	$('#content-game').attr("data",data);
	$('#content-game').show();
	$('#overlayOn').hide();
	
	});
	resize();
	
}

function first(){
	$('#firstScreen').hide();
	skip();
}

$( document ).ready(function() {
	firstC();
});

$( window ).resize(function() {
	resize();
});


</script>




</body>
</html>
