
<html>
<head>
<link rel="stylesheet" type="text/css"
	href="http://www.quantumstreams.net/css/bootstrap.css">
<title>Quantum Streams</title>
<style>
.page-empty {
	background-image:
		url("http://bnrfilms.in/wp-content/uploads/2014/08/website-background-small3.jpg");
	background-size: 100% 100%;
	margin: 0;
}
</style>
</head>
<body>
	<script src="http://www.quantumstreams.net/css/jquery-2.1.1.js"></script>
	<div style="padding: 0; margin: 0; width: 100%;" class="container">
		<div class="col-xs-12 col-sm-12 col-md-12"
			style="background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.8); border: 1px #999 solid; color: white;">

			<div class="" style="float: left;">
				<a href="<?php echo $this->getBaseUrl();?>"><img
					src="http://www.quantumstreams.net/logo_q.png"
					style="height: 60px; padding: 10px;" /></a>
			</div>
		</div>
		<div style="padding: 0" class="col-xs-12 col-sm-12 col-md-12">

			<div
				style="padding: 0;overflow:hidden; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2); opacity: 0; border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe2">
				
				
<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 1 -->
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="5762717689"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>



			<div class="col-xs-8 col-sm-8 col-md-8"
				style="background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.7); color: white; border: 1px #999 solid;">

				<div style="padding: 0;" class="col-xs-12 col-sm-12 col-md-12">
					<div id="firstScreen"
						style="display: block; padding: 25px; width: 100%; text-align: center; height: 100%; background: no-repeat scroll center center rgba(0, 0, 0, 0.7); z-index: 9999;">
						<h1 style="padding: 10px;">Welcome to QuantumStreams.net</h1>
						<h2>where things are never the same twice.</h2>
						<h3>Randomize Your World</h3>
						<h1 style="color: blue;">
							<a onclick="first();" style="cursor: pointer">Click to play :)</a>
						</h1>

						<p style="color: red;">THIS IS BETA VERSION - PROFILES ARE NOT
							IMPLEMENTED YET (just click and play)</p>

						<h6>Have fun and enjoy new and entertaining stream links.</h6>
						<h7 style="float:right;"> Best regards, QuantumStreams.Net </h7>
					</div>
				</div>
			</div>


			<div
				style="overflow: hidden; padding: 0; margin-bottom: 4px; background: none repeat scroll 0px 0px rgba(0, 0, 0, 0.2); opacity: 0; border: 1px #999 solid;"
				class="col-xs-2 col-sm-2 col-md-2" id="ovoJe">

				<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Quantum 2 -->
				<ins class="adsbygoogle"
					style="display: inline-block; width: 300px; height: 600px"
					data-ad-client="ca-pub-2132701630366122" data-ad-slot="7239450882"></ins>
				<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
			</div>

		</div>
	</div>

	<script>


</script>




</body>
</html>
